sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tKj3kR1f5VzYoBuFdKW
    access-key-secret: TevVi33rxloT7zpzSp97JFrpZZ1ADt
    bucket-name: java-ai-4422
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10